const logic_BP = {
    1: "BlueBan",
    2: "RedBan",
    3: "BluePick",
    4: "RedPick",
    5: "RedBan",
    6: "BlueBan",
    7: "RedPick",
    8: "BluePick",
    9: "BluePick",
    10: "RedPick",
    11: "RedPick",
    12: "BluePick",
    13: "BlueBan",
    14: "RedBan",
    15: "BlueBan",
    16: "RedBan",
    17: "BluePick",
    18: "RedPick",
    19: "RedPick",
    20: "BluePick",
    21: "RedBan",
    22: "BlueBan",
    23: "RedPick",
    24: "BluePick",
    25: "BluePick",
    26: "RedPick",
};

export { logic_BP };